from enum import Enum
import mss

monitor = mss.mss().monitors[1]

M2_WIDTH = 1728
M2_HEIGHT = 1117
M2_TOP_OFFSET = 37
IS_M2 = (monitor['width'] == M2_WIDTH)

SCREEN_WIDTH = monitor['width']
SCREEN_HEIGHT = monitor['height']
SCREEN_TOP = M2_TOP_OFFSET if IS_M2 else 0
SCREEN_LEFT = 0

RUNELITE_SIDEBAR_WIDTH = 30
GAME_LEFT = SCREEN_LEFT
GAME_TOP = SCREEN_TOP
GAME_WIDTH = SCREEN_WIDTH - RUNELITE_SIDEBAR_WIDTH
GAME_HEIGHT = SCREEN_HEIGHT - SCREEN_TOP

# todo: below should be converted to enum

BANK_BOTTOM_OFFSET = 170
BANK_WIDTH = 490
BANK_HEIGHT = 800
BANK_LEFT = SCREEN_LEFT + (GAME_WIDTH - BANK_WIDTH) / 2
BANK_TOP = SCREEN_TOP + (GAME_HEIGHT - BANK_HEIGHT - BANK_BOTTOM_OFFSET) / 2

MINIMAP_WIDTH = 215
MINIMAP_HEIGHT = 172
MINIMAP_LEFT = SCREEN_LEFT + GAME_WIDTH - MINIMAP_WIDTH
MINIMAP_TOP = SCREEN_TOP

CONTROL_PANEL_WIDTH = 246
CONTROL_PANEL_HEIGHT = 334
CONTROL_PANEL_LEFT = SCREEN_LEFT + GAME_WIDTH - CONTROL_PANEL_WIDTH
CONTROL_PANEL_TOP = SCREEN_TOP + GAME_HEIGHT - CONTROL_PANEL_HEIGHT

CHAT_WIDTH = 520
CHAT_HEIGHT = 200
CHAT_LEFT = SCREEN_LEFT
CHAT_TOP = SCREEN_TOP + GAME_HEIGHT - CHAT_HEIGHT

REWARD_RIGHT_OFFSET = 56
REWARD_BOTTOM_OFFSET = 162
REWARD_WIDTH = 234
REWARD_HEIGHT = 194
REWARD_LEFT = SCREEN_LEFT + (GAME_WIDTH - REWARD_WIDTH - REWARD_RIGHT_OFFSET) / 2
REWARD_TOP = SCREEN_TOP + (GAME_HEIGHT - REWARD_HEIGHT - REWARD_BOTTOM_OFFSET) / 2

TP_MENU_RIGHT_OFFSET = 40
TP_MENU_BOTTOM_OFFSET = 154
TP_MENU_WIDTH = 488
TP_MENU_HEIGHT = 306
TP_MENU_LEFT = SCREEN_LEFT + (GAME_WIDTH - TP_MENU_WIDTH - TP_MENU_RIGHT_OFFSET) / 2
TP_MENU_TOP = SCREEN_TOP + (GAME_HEIGHT - TP_MENU_HEIGHT - TP_MENU_BOTTOM_OFFSET) / 2


# todo: coordinates should be specified in scaled XY (0.0-1.0, 0.0-1.0)
def rescale_coord(x, y):
    if SCREEN_WIDTH == M2_WIDTH:
        return x, y
    else:
        ratio_x = GAME_WIDTH / (M2_WIDTH - RUNELITE_SIDEBAR_WIDTH)
        ratio_y = GAME_HEIGHT / (M2_HEIGHT - M2_TOP_OFFSET)
        return round(ratio_x * x), round(ratio_y * (y - M2_TOP_OFFSET))


def slice2d(p0, p1):
    return slice(2 * p0[1], 2 * p1[1]), slice(2 * p0[0], 2 * p1[0])


class Player(Enum):
    POSITION = rescale_coord(855, 585)


class Interface(Enum):
    COMBAT_TAB = CONTROL_PANEL_LEFT + 24, CONTROL_PANEL_TOP + 18
    STATS_TAB = CONTROL_PANEL_LEFT + 57, CONTROL_PANEL_TOP + 18
    QUEST_TAB = CONTROL_PANEL_LEFT + 90, CONTROL_PANEL_TOP + 18
    INVENTORY_TAB = CONTROL_PANEL_LEFT + 123, CONTROL_PANEL_TOP + 18
    EQUIPMENT_TAB = CONTROL_PANEL_LEFT + 156, CONTROL_PANEL_TOP + 18
    PRAYER_TAB = CONTROL_PANEL_LEFT + 189, CONTROL_PANEL_TOP + 18
    MAGIC_TAB = CONTROL_PANEL_LEFT + 222, CONTROL_PANEL_TOP + 18

    CLAN_TAB = CONTROL_PANEL_LEFT + 24, CONTROL_PANEL_TOP + 316
    FRIEND_TAB = CONTROL_PANEL_LEFT + 57, CONTROL_PANEL_TOP + 316
    IGNORE_TAB = CONTROL_PANEL_LEFT + 90, CONTROL_PANEL_TOP + 316
    LOGOUT_TAB = CONTROL_PANEL_LEFT + 123, CONTROL_PANEL_TOP + 316
    OPTIONS_TAB = CONTROL_PANEL_LEFT + 156, CONTROL_PANEL_TOP + 316
    EMOTE_TAB = CONTROL_PANEL_LEFT + 189, CONTROL_PANEL_TOP + 316
    MUSIC_TAB = CONTROL_PANEL_LEFT + 222, CONTROL_PANEL_TOP + 316

    BANK_CLOSE = BANK_LEFT + 470, BANK_TOP + 17


class Minimap(Enum):
    COMPASS = MINIMAP_LEFT + 54, MINIMAP_TOP + 20
    HEALTH = MINIMAP_LEFT + 39, MINIMAP_TOP + 58
    PRAYER = MINIMAP_LEFT + 39, MINIMAP_TOP + 93
    RUN = MINIMAP_LEFT + 50, MINIMAP_TOP + 126
    SPECIAL = MINIMAP_LEFT + 73, MINIMAP_TOP + 151


# dx = 26, dy = 24
class StandardSpellbook(Enum):
    HOME_TELEPORT = CONTROL_PANEL_LEFT + 45, CONTROL_PANEL_TOP + 48


# dx = 40, dy = 27
class ArceuusSpellbook(Enum):
    HOME_TELEPORT = CONTROL_PANEL_LEFT + 45, CONTROL_PANEL_TOP + 48
    RESURRECT_GREATER_GHOST = CONTROL_PANEL_LEFT + 84, CONTROL_PANEL_TOP + 212
    RESURRECT_GREATER_SKELETON = CONTROL_PANEL_LEFT + 124, CONTROL_PANEL_TOP + 212
    RESURRECT_GREATER_ZOMBIE = CONTROL_PANEL_LEFT + 164, CONTROL_PANEL_TOP + 212


# dx = 37, dy = 37
class Prayer(Enum):
    PROTECT_FROM_MAGIC = CONTROL_PANEL_LEFT + 82, CONTROL_PANEL_TOP + 27
    PROTECT_FROM_MISSILES = CONTROL_PANEL_LEFT + 119, CONTROL_PANEL_TOP + 27
    PROTECT_FROM_MELEE = CONTROL_PANEL_LEFT + 156, CONTROL_PANEL_TOP + 27
    EAGLE_EYE = CONTROL_PANEL_LEFT + 193, CONTROL_PANEL_TOP + 27
    MYSTIC_MIGHT = CONTROL_PANEL_LEFT + 45, CONTROL_PANEL_TOP + 64
    PIETY = CONTROL_PANEL_LEFT + 82, CONTROL_PANEL_TOP + 101


class BarrowsCoord(Enum):
    SPADE = CONTROL_PANEL_LEFT + 53, CONTROL_PANEL_TOP + 52  # todo: replace usages with Inventory.ITEM_1_1
    REWARDS_CLOSE = REWARD_LEFT + 218, REWARD_TOP + 18


class CerberusCoord(Enum):
    WALK1 = rescale_coord(850, 50)
    WALK2 = rescale_coord(750, 90)
    WALK3 = rescale_coord(850, 215)


class HealCoord(Enum):
    WALK1 = rescale_coord(700, 302)
    PRAYER_ALTAR = rescale_coord(1292, 68)
    HEALER = rescale_coord(805, 520)
    BANK_CHEST = rescale_coord(1080, 524)


class TeleportCoord(Enum):
    TELEPORT_WIZARD = rescale_coord(695, 255)

    SEARCH_BUTTON = TP_MENU_LEFT + 24, TP_MENU_TOP + 17
    SEARCH_FIRST_RESULT = TP_MENU_LEFT + 217, TP_MENU_TOP + 52
    SEARCH_SECOND_RESULT = TP_MENU_LEFT + 217, TP_MENU_TOP + 827


class ScreenRegion(Enum):
    DAMAGE_UI = slice2d((2, SCREEN_TOP + 40), (132, SCREEN_TOP + 60))
    HOVER_ACTION = slice2d((0, SCREEN_TOP), (400, SCREEN_TOP + 20))
    LATEST_CHAT = slice2d((7, CHAT_TOP + 136), (497, CHAT_TOP + 155))

    HITPOINTS = slice2d((MINIMAP_LEFT + 6, MINIMAP_TOP + 57), (MINIMAP_LEFT + 26, MINIMAP_TOP + 69))
    PRAYER = slice2d((MINIMAP_LEFT + 6, MINIMAP_TOP + 91), (MINIMAP_LEFT + 26, MINIMAP_TOP + 103))
    RUN_ENERGY = slice2d((MINIMAP_LEFT + 15, MINIMAP_TOP + 123), (MINIMAP_LEFT + 35, MINIMAP_TOP + 135))
    SPEC_ENERGY = slice2d((MINIMAP_LEFT + 39, MINIMAP_TOP + 149), (MINIMAP_LEFT + 59, MINIMAP_TOP + 161))

    MINIMAP = slice2d((MINIMAP_LEFT, MINIMAP_TOP), (MINIMAP_LEFT + MINIMAP_WIDTH, MINIMAP_TOP + MINIMAP_HEIGHT))
    CONTROL_PANEL = slice2d((CONTROL_PANEL_LEFT, CONTROL_PANEL_TOP), (CONTROL_PANEL_LEFT + CONTROL_PANEL_WIDTH, CONTROL_PANEL_TOP + CONTROL_PANEL_HEIGHT))
    CHAT = slice2d((CHAT_LEFT, CHAT_TOP), (CHAT_LEFT + CHAT_WIDTH, CHAT_TOP + CHAT_HEIGHT))
    STATUS = slice2d((SCREEN_LEFT, SCREEN_TOP), (SCREEN_LEFT + 221, SCREEN_TOP + 173))
    EXP_BAR = slice2d((MINIMAP_LEFT - 153, MINIMAP_TOP + 2), (MINIMAP_LEFT - 31, MINIMAP_TOP + 32))

    RUNELITE_SIDEBAR = slice2d((GAME_WIDTH, SCREEN_TOP), (SCREEN_WIDTH, SCREEN_TOP + GAME_HEIGHT))
